In [0]:
import numpy as np

In [2]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)         

[[0. 0.]
 [0. 0.]]


In [3]:
b = np.ones((1,2))    # Create an array of all ones
print(b)

[[1. 1.]]


In [4]:
c = np.full((2,2), 7)  # Create a constant array
print(c)  

[[7 7]
 [7 7]]


In [5]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)      

[[1. 0.]
 [0. 1.]]


In [6]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)   

[[0.16392654 0.16340682]
 [0.63614289 0.37039996]]
