In [0]:
import numpy as np

In [2]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print (b)  

[[1 2 3]
 [4 5 6]]


In [5]:
print(b[0,0])
print(b[0,1])
print(b[0,2])
print(b[1,0])
print(b[1,1])
print(b[1,2])


1
2
3
4
5
6


In [6]:
b[0,0] = 7
print (b)

[[7 2 3]
 [4 5 6]]
