In [0]:
import numpy as np

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])            # create an array with shape (3,4)

In [4]:
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
'''......    slicing of array
 NOTE : The weight of 1st row is 0, 2nd row is 1 and 3rd row is 2
[[ 1  2  3  4]__________ 0th row
 [ 5  6  7  8]__________ 1st row
 [ 9 10 11 12]]_________ 2nd row       .....'''

b = a [:2]                # sliced just before 2nd row 
print (b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
c = a [1:]              # print from 1st row onwards 
print (c)

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
d = a[1:2]              # to print 1st row
print (d)

[[5 6 7 8]]


In [18]:
d1 = a[2:3]            # to print 2nd row
print (d1)

[[ 9 10 11 12]]


In [21]:
print(a[0, 1])            

2


In [22]:
e = a[:2, 1:3]           # Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2;
print (e)

[[2 3]
 [6 7]]


In [23]:
print(a[0, 1])   
e[0, 0] = 77     # e[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77
